WITH source AS (
    SELECT * FROM {{ source('silver_clean', 'EV_REGISTRATIONS_STAGE') }}
)

SELECT
    DOL_VEHICLE_ID,
    VIN_PARTIAL,
    MAKE,
    MODEL,
    MODEL_YEAR,
    EV_TYPE_FULL,
    CAFV_ELIGIBILITY,
    ELECTRIC_RANGE_MILES,
    IS_RANGE_UNKNOWN,
    BASE_MSRP_USD,
    IS_MSRP_UNKNOWN,
    COUNTY,
    CITY,
    STATE_CODE,
    ZIP_CODE,
    IS_WA_RECORD,
    VEHICLE_LATITUDE,
    VEHICLE_LONGITUDE,
    LEGISLATIVE_DISTRICT,
    ELECTRIC_UTILITY,
    CENSUS_TRACT_2020,
    SILVER_LOAD_TS,
    BRONZE_ROW_HASH,
    SOURCE_FILE
FROM source
