USE ROLE SYSADMIN;
USE WAREHOUSE WH_TRANSFORM;

-- ============================================================
-- STEP 1: Rename standard tables as backups
-- ============================================================
ALTER TABLE EV_GOLD.SERVING.FACT_EV_REGISTRATIONS RENAME TO EV_GOLD.SERVING.FACT_EV_REGISTRATIONS_STD;
ALTER TABLE EV_GOLD.SERVING.DIM_VEHICLE RENAME TO EV_GOLD.SERVING.DIM_VEHICLE_STD;
ALTER TABLE EV_GOLD.SERVING.DIM_GEOGRAPHY RENAME TO EV_GOLD.SERVING.DIM_GEOGRAPHY_STD;
ALTER TABLE EV_GOLD.SERVING.AGG_YOY_GROWTH RENAME TO EV_GOLD.SERVING.AGG_YOY_GROWTH_STD;
ALTER TABLE EV_GOLD.SERVING.AGG_REGIONAL_ADOPTION RENAME TO EV_GOLD.SERVING.AGG_REGIONAL_ADOPTION_STD;

-- ============================================================
-- STEP 2: Create Iceberg versions (Snowflake-managed storage)
-- ============================================================
CREATE ICEBERG TABLE EV_GOLD.SERVING.FACT_EV_REGISTRATIONS
    EXTERNAL_VOLUME = 'SNOWFLAKE_MANAGED'
    CATALOG = 'SNOWFLAKE'
    AS SELECT * FROM EV_GOLD.SERVING.FACT_EV_REGISTRATIONS_STD;

CREATE ICEBERG TABLE EV_GOLD.SERVING.DIM_VEHICLE
    EXTERNAL_VOLUME = 'SNOWFLAKE_MANAGED'
    CATALOG = 'SNOWFLAKE'
    AS SELECT * FROM EV_GOLD.SERVING.DIM_VEHICLE_STD;

CREATE ICEBERG TABLE EV_GOLD.SERVING.DIM_GEOGRAPHY
    EXTERNAL_VOLUME = 'SNOWFLAKE_MANAGED'
    CATALOG = 'SNOWFLAKE'
    AS SELECT * FROM EV_GOLD.SERVING.DIM_GEOGRAPHY_STD;

CREATE ICEBERG TABLE EV_GOLD.SERVING.AGG_YOY_GROWTH
    EXTERNAL_VOLUME = 'SNOWFLAKE_MANAGED'
    CATALOG = 'SNOWFLAKE'
    AS SELECT * FROM EV_GOLD.SERVING.AGG_YOY_GROWTH_STD;

CREATE ICEBERG TABLE EV_GOLD.SERVING.AGG_REGIONAL_ADOPTION
    EXTERNAL_VOLUME = 'SNOWFLAKE_MANAGED'
    CATALOG = 'SNOWFLAKE'
    AS SELECT * FROM EV_GOLD.SERVING.AGG_REGIONAL_ADOPTION_STD;

-- ============================================================
-- STEP 3: Drop backup standard tables
-- ============================================================
DROP TABLE EV_GOLD.SERVING.FACT_EV_REGISTRATIONS_STD;
DROP TABLE EV_GOLD.SERVING.DIM_VEHICLE_STD;
DROP TABLE EV_GOLD.SERVING.DIM_GEOGRAPHY_STD;
DROP TABLE EV_GOLD.SERVING.AGG_YOY_GROWTH_STD;
DROP TABLE EV_GOLD.SERVING.AGG_REGIONAL_ADOPTION_STD;

-- ============================================================
-- STEP 4: Verify Iceberg tables
-- ============================================================
SHOW ICEBERG TABLES IN SCHEMA EV_GOLD.SERVING;
