USE ROLE SYSADMIN;

-- ============================================================
-- EVENT-DRIVEN ORCHESTRATION: Bronze → Silver → Gold
-- All tasks in EV_SILVER.CLEAN (Snowflake requires same schema for DAG)
-- ============================================================

-- STREAM: Detects new data in Bronze
CREATE OR REPLACE STREAM EV_BRONZE.RAW.STM_EV_POPULATION_RAW
  ON TABLE EV_BRONZE.RAW.EV_POPULATION_RAW
  APPEND_ONLY = TRUE;

-- TASK 1 (ROOT): Bronze → Silver Stage
-- Polls every 5 min, fires ONLY when stream has data
-- FIX: Consumes stream after SP call to prevent infinite re-triggering
CREATE OR REPLACE TASK EV_SILVER.CLEAN.TSK_1_BRONZE_TO_SILVER_STAGE
  WAREHOUSE = WH_INGEST
  SCHEDULE = '5 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('EV_BRONZE.RAW.STM_EV_POPULATION_RAW')
AS
  BEGIN
    CALL EV_SILVER.CLEAN.SP_BRONZE_TO_SILVER_STAGE();
    CREATE OR REPLACE TEMPORARY TABLE EV_SILVER.CLEAN._STREAM_CONSUME AS
      SELECT * FROM EV_BRONZE.RAW.STM_EV_POPULATION_RAW;
  END;

-- TASK 2: dbt Silver (build = run + test)
CREATE OR REPLACE TASK EV_SILVER.CLEAN.TSK_2_DBT_SILVER
  WAREHOUSE = WH_TRANSFORM
  AFTER EV_SILVER.CLEAN.TSK_1_BRONZE_TO_SILVER_STAGE
AS
  EXECUTE DBT PROJECT EV_SILVER.CLEAN.EV_PIPELINE_SILVER ARGS = 'build';

-- TASK 3: dbt Gold (build = run + test)
CREATE OR REPLACE TASK EV_SILVER.CLEAN.TSK_3_DBT_GOLD
  WAREHOUSE = WH_TRANSFORM
  AFTER EV_SILVER.CLEAN.TSK_2_DBT_SILVER
AS
  EXECUTE DBT PROJECT EV_GOLD.SERVING.EV_PIPELINE_GOLD ARGS = 'build';

-- TASK 4 (LEAF): Audit log
CREATE OR REPLACE TASK EV_SILVER.CLEAN.TSK_4_AUDIT_LOG
  WAREHOUSE = WH_INGEST
  AFTER EV_SILVER.CLEAN.TSK_3_DBT_GOLD
AS
  INSERT INTO EV_BRONZE.RAW.LOAD_AUDIT (
    LOAD_START_TIME, LOAD_END_TIME, FILE_NAME,
    RECORDS_LOADED, LOAD_STATUS
  )
  SELECT
    DATEADD('minute', -10, CURRENT_TIMESTAMP()),
    CURRENT_TIMESTAMP(),
    'EVENT_DRIVEN_PIPELINE_RUN',
    (SELECT COUNT(*) FROM EV_GOLD.SERVING.FACT_EV_REGISTRATIONS),
    'SUCCESS';

-- RESUME (leaf → root order)
ALTER TASK EV_SILVER.CLEAN.TSK_4_AUDIT_LOG RESUME;
ALTER TASK EV_SILVER.CLEAN.TSK_3_DBT_GOLD RESUME;
ALTER TASK EV_SILVER.CLEAN.TSK_2_DBT_SILVER RESUME;
ALTER TASK EV_SILVER.CLEAN.TSK_1_BRONZE_TO_SILVER_STAGE RESUME;

-- ============================================================
-- MANUAL TRIGGER (for testing)
-- ============================================================
-- EXECUTE TASK EV_SILVER.CLEAN.TSK_1_BRONZE_TO_SILVER_STAGE;

-- ============================================================
-- MONITORING
-- ============================================================
-- SHOW TASKS IN SCHEMA EV_SILVER.CLEAN;
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
--   SCHEDULED_TIME_RANGE_START => DATEADD('day', -1, CURRENT_TIMESTAMP())
-- )) WHERE NAME LIKE 'TSK_%' ORDER BY SCHEDULED_TIME DESC;

-- ============================================================
-- SUSPEND ALL (for maintenance)
-- ============================================================
-- ALTER TASK EV_SILVER.CLEAN.TSK_1_BRONZE_TO_SILVER_STAGE SUSPEND;
-- ALTER TASK EV_SILVER.CLEAN.TSK_2_DBT_SILVER SUSPEND;
-- ALTER TASK EV_SILVER.CLEAN.TSK_3_DBT_GOLD SUSPEND;
-- ALTER TASK EV_SILVER.CLEAN.TSK_4_AUDIT_LOG SUSPEND;
