USE ROLE SYSADMIN;
USE WAREHOUSE WH_INGEST;

INSERT INTO EV_BRONZE.RAW.LOAD_AUDIT (
    LOAD_START_TIME,
    LOAD_END_TIME,
    FILE_NAME,
    RECORDS_LOADED,
    RECORDS_FAILED,
    LOAD_STATUS
)
SELECT
    r.LOAD_TIMESTAMP,
    CURRENT_TIMESTAMP(),
    r.FILE_NAME,
    ARRAY_SIZE(r.RAW_DATA:data),
    0,
    'SUCCESS'
FROM EV_BRONZE.RAW.EV_POPULATION_RAW r;

SELECT * FROM EV_BRONZE.RAW.LOAD_AUDIT ORDER BY AUDIT_ID;
