USE ROLE SYSADMIN;
USE WAREHOUSE WH_INGEST;

COPY INTO EV_BRONZE.RAW.EV_POPULATION_RAW (RAW_DATA, FILE_NAME)
FROM (
    SELECT
        $1,
        METADATA$FILENAME
    FROM @EV_BRONZE.RAW.STG_EV_JSON/ElectricVehiclePopulationData.json
)
FILE_FORMAT = (TYPE = 'JSON' STRIP_OUTER_ARRAY = FALSE)
ON_ERROR = 'ABORT_STATEMENT';

SELECT
    COUNT(*)                                AS ROWS_LOADED,
    MAX(RAW_DATA:meta:view:name::STRING)    AS DATASET_NAME,
    MAX(ARRAY_SIZE(RAW_DATA:data))          AS DATA_ARRAY_RECORD_COUNT,
    MAX(LOAD_TIMESTAMP)                     AS LOAD_TIMESTAMP
FROM EV_BRONZE.RAW.EV_POPULATION_RAW;
